site_name: Lukas Jan Stroemsdoerfer
site_description: Acing your Application
site_url: https://test.com/
theme:
  name: material
  palette:
    scheme: slate
    primary: teal
    accent: teal
  icon:
    repo: fontawesome/brands/github-alt
  favicon: /presentation/docs/img/logo.png
  language: en
  features:
    - toc.integrate
repo_name: LJStroemsdoerfer/applyiverse
repo_url: https://github.com/LJStroemsdoerfer/applyiverse.git
edit_uri: ''
plugins:
- search
- mkdocs-jupyter
    theme: dark
    kernel_name: python3
nav:
- Home: index.md
- Proposition: content/proposition.md
- Challenges: content/challenges.md
- Showcase: content/showcase.ipynb
markdown_extensions:
- toc:
    permalink: false
- markdown.extensions.codehilite:
    guess_lang: true
- markdown_include.include:
    base_path: docs
- admonition
- codehilite
- extra
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_div_format ''
- pymdownx.tabbed
extra:
  social:
  - icon: fontawesome/brands/github-alt
    link: https://github.com/LJStroemsdoerfer
extra_css:
- css/main.css
extra_javascript:
- https://unpkg.com/mermaid@8.4.6/dist/mermaid.min.js
- js/main.js
