name: publish website
on:
  push:
    branches:
      - main
jobs:
  update-readme-with-blog:
    runs-on: ubuntu-latest
    name: update index page with latest blog posts
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://medium.com/feed/@ljstroemsdoerfer"
          readme_path: presentation/docs/index.md
      - run: |
          git config --global user.name 'LJStroemsdoerfer'
          git config --global user.email 'LJStroemsdoerfer@users.noreply.github.com'
          git add presentation/docs/index.md
          git commit -m "updated blog post"
          git push origin main
    
  deploy:
    runs-on: ubuntu-latest
    name: publish website to GitHub Pages
    needs: update-readme-with-blog
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - run: pip install mkdocs-material
      - run: pip install markdown-include
      - run: pip install mkdocs-markdownextradata-plugin
      - run: mkdocs gh-deploy --force --config-file presentation/mkdocs.yml
